spring.application.name=RealEstate

spring.datasource.url=jdbc:mysql://localhost:3306/realestate
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=never

jwt.secret=4a8f3b2c9d1e6f7a0b5c8d2e4f9a1b3c6d8e0f2a4b7c9d1e3f5a7b0c2d4e6f8i
jwt.expiration=86400000

app.file-upload-dir=uploads